// David Reyes — Champion in Mississauga
// 112 contacts, 11 deposits, 3 months in
// Goal: 25 deposits to open the Mississauga campus

const CHAMPION = {
  name: "David Reyes",
  short: "David",
  initials: "DR",
  geo: "Mississauga · Port Credit",
  joined: "Aug 2025",
  email: "david@reyes.family",
  avatar: "https://i.pravatar.cc/120?img=33",
};

// Stages match alphahub/src/lib/constants/pipeline.ts exactly
const STAGES = [
  { id: "interested", label: "Interested",  cls: "stage-interested" },
  { id: "shadow-day", label: "Shadow Day",  cls: "stage-shadow" },
  { id: "committed",  label: "Committed",   cls: "stage-deposited" },
  { id: "enrolled",   label: "Enrolled",    cls: "stage-enrolled" },
  { id: "lost",       label: "Lost",        cls: "stage-cold" },
];

const SIGNALS = [
  { id: "faq",       label: "Sent FAQ" },
  { id: "11",        label: "1:1 conversation" },
  { id: "intro",     label: "Introduced to parent" },
  { id: "deposit",   label: "Shared deposit link" },
  { id: "tour",      label: "Toured Austin/Brownsville" },
  { id: "shadow",    label: "Booked shadow day" },
];

const CONCERNS = [
  "tuition", "pace", "accreditation", "screen time",
  "socialization", "transcripts", "religion", "spouse buy-in",
];

const CONTACTS = [
  {
    id: "c01",
    name: "Priya Nair",
    family: "Nair-Mehta",
    kids: ["Aanya, 9", "Vir, 6"],
    neighborhood: "Port Credit",
    referrer: "Walked in at Sept BBQ",
    stage: "interested",
    heat: 5,
    lastTouch: "2 days ago",
    daysSince: 2,
    nextAction: "Send shadow day invite for Nov 22",
    signals: ["faq", "11"],
    concerns: ["tuition", "accreditation"],
    notes: "Engineer at Shopify. Husband Karthik is more skeptical — wants to see academic outcomes. She's the decision-maker on schooling. Loved the 'Why Alpha' essay; asked sharp questions about the 2hr learning model.",
    avatar: "PN",
    email: "priya.nair@example.com",
    phone: "(416) 555-0182",
    timeline: [
      { type: "stage", when: "Today", title: "Heat raised to 5", body: "After Saturday coffee — said she's ready to bring Karthik to a shadow day." },
      { type: "msg",   when: "2 days ago", title: "1:1 conversation logged", body: "Coffee at Birds & Beans. 90 min. Walked through the 2hr learning model and reward economy. Concerns shifted from skepticism to logistics. Wants to know about transcripts for Aanya going to high school." },
      { type: "msg",   when: "Sep 22", title: "Sent: 'Why Alpha for STEM kids'", body: "Marked opened (3x). She forwarded to Karthik per text reply." },
      { type: "event", when: "Sep 14", title: "RSVP'd: September Block BBQ", body: "Came with both kids. Aanya hit it off with Maya R." },
      { type: "stage", when: "Sep 14", title: "Stage → Interested", body: "From cold." },
    ],
  },
  {
    id: "c02",
    name: "Marcus & Lena Okafor",
    family: "Okafor",
    kids: ["Zara, 8"],
    neighborhood: "Lorne Park",
    referrer: "Intro from Sara K.",
    stage: "shadow-day",
    heat: 5,
    lastTouch: "Yesterday",
    daysSince: 1,
    nextAction: "Confirm Nov 14 shadow day logistics",
    signals: ["faq", "11", "shadow", "intro"],
    concerns: ["pace"],
    notes: "Both parents are physicians. Zara is academically gifted, currently bored at TFS. Likely to deposit if shadow day goes well. Lena is the warmer parent.",
    avatar: "MO",
    email: "lena.okafor@example.com",
    timeline: [
      { type: "msg", when: "Yesterday", title: "Confirmed shadow day", body: "Booked for Nov 14, 9am–2pm at Brownsville campus. Zara is excited." },
      { type: "stage", when: "3 days ago", title: "Stage → Shadow Day", body: "" },
    ],
  },
  {
    id: "c03",
    name: "Hyun-Jin Park",
    family: "Park",
    kids: ["Daniel, 11", "Sophie, 8"],
    neighborhood: "Mineola",
    referrer: "From the website",
    stage: "committed",
    heat: 4,
    lastTouch: "Last week",
    daysSince: 6,
    nextAction: "Send onboarding doc, intro to other deposited families",
    signals: ["faq", "11", "deposit", "tour"],
    concerns: [],
    notes: "Took the family to visit Brownsville campus on their own dime. Decision was made on the plane home. Daniel is dyslexic — wants to know about accommodation.",
    avatar: "HP",
    email: "hyunjin@example.com",
    timeline: [],
  },
  {
    id: "c04",
    name: "Ade & Tomi Adebayo",
    family: "Adebayo",
    kids: ["Folake, 7", "Tunde, 5"],
    neighborhood: "Clarkson",
    referrer: "Met at Park Day",
    stage: "interested",
    heat: 4,
    lastTouch: "5 days ago",
    daysSince: 5,
    nextAction: "Invite to Nov 22 Saturday workshop",
    signals: ["faq"],
    concerns: ["religion", "socialization"],
    notes: "Pastor's family. Want to know how Alpha handles values education. Said the kids would need a faith-based supplement at home — open to that.",
    avatar: "AA",
    email: "ade@example.com",
    timeline: [],
  },
  {
    id: "c05",
    name: "Mei Tanaka",
    family: "Tanaka-Wright",
    kids: ["Kai, 10"],
    neighborhood: "Port Credit",
    referrer: "Intro from Priya N.",
    stage: "interested",
    heat: 3,
    lastTouch: "8 days ago",
    daysSince: 8,
    nextAction: "Re-engage — send Kai-aged kid testimonial",
    signals: ["faq", "11"],
    concerns: ["tuition", "spouse buy-in"],
    notes: "Single mom. Tuition is the gate. We discussed financial aid but she hasn't applied. Husband out of picture but contributes.",
    avatar: "MT",
    email: "mei@example.com",
    timeline: [],
  },
  {
    id: "c06",
    name: "Sarah & Jonah Klein",
    family: "Klein",
    kids: ["Eli, 6"],
    neighborhood: "Lorne Park",
    referrer: "Met at synagogue",
    stage: "committed",
    heat: 5,
    lastTouch: "2 weeks ago",
    daysSince: 14,
    nextAction: "Just check in — maintain warmth before Sept",
    signals: ["faq", "11", "deposit", "tour", "intro"],
    concerns: [],
    notes: "First family to deposit. Power evangelists. Have introduced 4 other families.",
    avatar: "SK",
    email: "sarah.klein@example.com",
    timeline: [],
  },
  {
    id: "c07",
    name: "Diego Vasquez",
    family: "Vasquez",
    kids: ["Mateo, 9", "Lucia, 7", "Sol, 4"],
    neighborhood: "Cooksville",
    referrer: "Cold inbound",
    stage: "lost",
    heat: 2,
    lastTouch: "12 days ago",
    daysSince: 12,
    nextAction: "Re-engage — invite to public event",
    signals: ["faq"],
    concerns: ["tuition", "accreditation"],
    notes: "Filled out the website form. One reply email exchange. Has not engaged since.",
    avatar: "DV",
    email: "diego@example.com",
    timeline: [],
  },
  {
    id: "c08",
    name: "Amara & Ben Thompson",
    family: "Thompson",
    kids: ["Naomi, 8", "Theo, 5"],
    neighborhood: "Port Credit",
    referrer: "Met at Park Day",
    stage: "shadow-day",
    heat: 4,
    lastTouch: "4 days ago",
    daysSince: 4,
    nextAction: "Follow up after Nov 8 shadow day",
    signals: ["faq", "11", "shadow"],
    concerns: ["accreditation"],
    notes: "Ben works in EdTech, very analytical. Wants the data on outcomes. I sent the Brownsville report.",
    avatar: "AT",
    email: "amara@example.com",
    timeline: [],
  },
  {
    id: "c09",
    name: "Rachel Singh",
    family: "Singh-Davis",
    kids: ["Ezra, 6", "Iris, 4"],
    neighborhood: "Mineola",
    referrer: "Intro from Sarah K.",
    stage: "interested",
    heat: 3,
    lastTouch: "11 days ago",
    daysSince: 11,
    nextAction: "Send 'screen time' FAQ",
    signals: ["faq"],
    concerns: ["screen time", "socialization"],
    notes: "",
    avatar: "RS",
    email: "rachel@example.com",
    timeline: [],
  },
  {
    id: "c10",
    name: "Wei & Lily Chen",
    family: "Chen",
    kids: ["Audrey, 9", "Felix, 6"],
    neighborhood: "Cooksville",
    referrer: "Block BBQ",
    stage: "committed",
    heat: 5,
    lastTouch: "1 week ago",
    daysSince: 7,
    nextAction: "Loop into the Mississauga depositors thread",
    signals: ["faq", "11", "deposit", "tour"],
    concerns: [],
    notes: "Visited Brownsville last month. Felix is the spark — Audrey will follow.",
    avatar: "WC",
    email: "wei@example.com",
    timeline: [],
  },
  {
    id: "c11",
    name: "Aleksandra Wojcik",
    family: "Wojcik",
    kids: ["Mira, 7"],
    neighborhood: "Lakeview",
    referrer: "Cold inbound",
    stage: "lost",
    heat: 1,
    lastTouch: "21 days ago",
    daysSince: 21,
    nextAction: "Probably dead. Last attempt: invite to public event.",
    signals: [],
    concerns: ["tuition"],
    notes: "",
    avatar: "AW",
    email: "ola@example.com",
    timeline: [],
  },
  {
    id: "c12",
    name: "Joon-ho Lee",
    family: "Lee-Park",
    kids: ["Min, 8"],
    neighborhood: "Erindale",
    referrer: "Intro from Hyun-Jin P.",
    stage: "interested",
    heat: 4,
    lastTouch: "3 days ago",
    daysSince: 3,
    nextAction: "Schedule 1:1 coffee",
    signals: ["faq"],
    concerns: ["pace"],
    notes: "Hyun-Jin's neighbor. Min is a coding kid — would thrive in Alpha's project track.",
    avatar: "JL",
    email: "joon@example.com",
    timeline: [],
  },
];

// Library content
const LIBRARY = [
  {
    id: "l01",
    type: "faq",
    typeLabel: "FAQ",
    title: "Is Alpha accredited? What about transcripts?",
    body: "Alpha is accredited through the Cognia accreditation organization, which is recognized by all U.S. universities and translates to Canadian institutions through standard equivalency processes. We issue official transcripts at the end of each year. Students leaving Alpha for traditional schools have transferred without credit loss in 100% of cases to date.",
    author: "Alpha HQ",
    sends: 47,
    helpfulness: 92,
    audience: ["skeptics", "high-grade"],
    concern: "accreditation",
  },
  {
    id: "l02",
    type: "faq",
    typeLabel: "FAQ",
    title: "How do you handle kids with learning differences (dyslexia, ADHD, gifted)?",
    body: "Alpha's adaptive AI tutors are uniquely well-suited for neurodiverse learners. Dyslexic students get audio-first instruction by default. ADHD kids benefit from short, intense focus blocks (25 min) with clear reward cycles. Gifted students aren't artificially capped — they progress at their actual pace.",
    author: "Sarah K. (Toronto Champion)",
    sends: 34,
    helpfulness: 88,
    audience: ["neurodiverse"],
    concern: "pace",
  },
  {
    id: "l03",
    type: "quote",
    typeLabel: "Testimonial",
    title: "From a Brownsville parent on the 2-hour day",
    body: "I was the most skeptical parent in the room. I'm a tenured professor — my whole life is built on classrooms. I gave it one semester. By March, my daughter was reading Tolstoy and asking if she could spend afternoons learning Mandarin. I have not opened a school argument since.",
    author: "Lakshmi V., parent of Anjali (Grade 4)",
    sends: 28,
    helpfulness: 96,
    audience: ["skeptics"],
    concern: "pace",
  },
  {
    id: "l04",
    type: "talking",
    typeLabel: "Talking Points",
    title: "Three things to say to the tuition-skeptic spouse",
    body: "(1) Compare against any private school, not against public — you'll be in line. (2) The reward economy is, in itself, a financial education most kids never get. (3) Ask: what would you pay to have your kid 2 grade levels ahead by spring?",
    author: "David R. (you)",
    sends: 19,
    helpfulness: 84,
    audience: ["spouse buy-in"],
    concern: "tuition",
  },
  {
    id: "l05",
    type: "data",
    typeLabel: "Data",
    title: "Brownsville 2024–25 outcomes report",
    body: "Cohort outperformed national 90th percentile in math and reading at every grade level. Average pace: 2.3x baseline. 94% of students enrolled the following year.",
    author: "Alpha HQ",
    sends: 41,
    helpfulness: 91,
    audience: ["skeptics", "data-driven"],
    concern: "accreditation",
  },
  {
    id: "l06",
    type: "quote",
    typeLabel: "Testimonial",
    title: "From a working mom on logistics",
    body: "The afternoons changed my life as much as my kids'. I get my afternoons back, the kids get real things to do. Tennis lessons, orchestra, the things we used to cram into weekends are just… how we live now.",
    author: "Amelia T., parent of two",
    sends: 22,
    helpfulness: 89,
    audience: ["working-parents"],
    concern: "tuition",
  },
  {
    id: "l07",
    type: "faq",
    typeLabel: "FAQ",
    title: "How is socialization handled with only 2 hours of structured time?",
    body: "The afternoon block is the social block — life skills workshops, group projects, sports, theater. It's far more social than a traditional school day, where 'socialization' is often just lining up for lunch.",
    author: "Alpha HQ",
    sends: 31,
    helpfulness: 87,
    audience: ["skeptics"],
    concern: "socialization",
  },
  {
    id: "l08",
    type: "talking",
    typeLabel: "Talking Points",
    title: "Pivoting from 'is this real?' to 'how would my kid fit?'",
    body: "Stop trying to sell the model. Ask the parent: 'tell me about your kid's last great week of school.' Then: 'what would you change?' Alpha sells itself once a parent describes their own kid honestly.",
    author: "David R. (you)",
    sends: 14,
    helpfulness: 90,
    audience: ["champions"],
    concern: "pace",
  },
  {
    id: "l09",
    type: "quote",
    typeLabel: "Testimonial",
    title: "From a religious family",
    body: "We worried Alpha would conflict with what we teach at home. The opposite. The afternoons gave us back the time to do scripture and family history — things public school left no room for.",
    author: "The Mendez family",
    sends: 11,
    helpfulness: 85,
    audience: ["religious"],
    concern: "religion",
  },
  {
    id: "l10",
    type: "faq",
    typeLabel: "FAQ",
    title: "What happens if my kid hates it after a month?",
    body: "We have a 60-day full-refund policy on the first year deposit. Roughly 6% of families withdraw in the first 60 days; the most common reason is logistics, not the model itself.",
    author: "Alpha HQ",
    sends: 17,
    helpfulness: 93,
    audience: ["skeptics"],
    concern: "tuition",
  },
];

const EVENTS = [
  {
    id: "e01",
    title: "Saturday Workshop: Why Alpha?",
    when: "Sat, Nov 22 · 10am",
    month: "NOV", day: "22",
    where: "Port Credit Library",
    desc: "Open Q&A for skeptical parents. Public event.",
    rsvps: 17,
    cap: 25,
    type: "public",
  },
  {
    id: "e02",
    title: "Shadow Day · Brownsville",
    when: "Fri, Nov 14 · all day",
    month: "NOV", day: "14",
    where: "Brownsville campus, Texas",
    desc: "Three Mississauga families flying down together.",
    rsvps: 3,
    cap: 8,
    type: "private",
  },
  {
    id: "e03",
    title: "Park Day · Lakeside",
    when: "Sun, Dec 7 · 2pm",
    month: "DEC", day: "07",
    where: "Lakeside Park",
    desc: "Casual meetup for families considering Alpha. Bring kids.",
    rsvps: 24,
    cap: 50,
    type: "public",
  },
  {
    id: "e04",
    title: "Founders' Coffee with Joe Liemandt",
    when: "Wed, Dec 17 · 7pm",
    month: "DEC", day: "17",
    where: "Mississauga Convention Ctr.",
    desc: "Alpha founder in town. Champion-only intro list.",
    rsvps: 31,
    cap: 60,
    type: "private",
  },
];

Object.assign(window, { CHAMPION, STAGES, SIGNALS, CONCERNS, CONTACTS, LIBRARY, EVENTS });
