-- Seed 53 geographies: 23 existing campuses + 30 pre-launch
-- Slugs are URL-safe lowercase identifiers for intake form URLs

INSERT INTO geographies (slug, name, region, country, status) VALUES
  -- Existing campuses (23)
  ('austin', 'Austin', 'South', 'US', 'existing-campus'),
  ('dallas', 'Dallas', 'South', 'US', 'existing-campus'),
  ('houston', 'Houston', 'South', 'US', 'existing-campus'),
  ('san-antonio', 'San Antonio', 'South', 'US', 'existing-campus'),
  ('miami', 'Miami', 'Southeast', 'US', 'existing-campus'),
  ('tampa', 'Tampa', 'Southeast', 'US', 'existing-campus'),
  ('orlando', 'Orlando', 'Southeast', 'US', 'existing-campus'),
  ('jacksonville', 'Jacksonville', 'Southeast', 'US', 'existing-campus'),
  ('atlanta', 'Atlanta', 'Southeast', 'US', 'existing-campus'),
  ('nashville', 'Nashville', 'South', 'US', 'existing-campus'),
  ('charlotte', 'Charlotte', 'Southeast', 'US', 'existing-campus'),
  ('raleigh', 'Raleigh', 'Southeast', 'US', 'existing-campus'),
  ('phoenix', 'Phoenix', 'West', 'US', 'existing-campus'),
  ('scottsdale', 'Scottsdale', 'West', 'US', 'existing-campus'),
  ('denver', 'Denver', 'West', 'US', 'existing-campus'),
  ('las-vegas', 'Las Vegas', 'West', 'US', 'existing-campus'),
  ('san-diego', 'San Diego', 'West', 'US', 'existing-campus'),
  ('los-angeles', 'Los Angeles', 'West', 'US', 'existing-campus'),
  ('chicago', 'Chicago', 'Midwest', 'US', 'existing-campus'),
  ('columbus', 'Columbus', 'Midwest', 'US', 'existing-campus'),
  ('toronto', 'Toronto', 'Ontario', 'CA', 'existing-campus'),
  ('vancouver', 'Vancouver', 'British Columbia', 'CA', 'existing-campus'),
  ('calgary', 'Calgary', 'Alberta', 'CA', 'existing-campus'),

  -- Pre-launch (30)
  ('boston', 'Boston', 'Northeast', 'US', 'pre-launch'),
  ('new-york', 'New York', 'Northeast', 'US', 'pre-launch'),
  ('washington-dc', 'Washington DC', 'Northeast', 'US', 'pre-launch'),
  ('philadelphia', 'Philadelphia', 'Northeast', 'US', 'pre-launch'),
  ('pittsburgh', 'Pittsburgh', 'Northeast', 'US', 'pre-launch'),
  ('minneapolis', 'Minneapolis', 'Midwest', 'US', 'pre-launch'),
  ('detroit', 'Detroit', 'Midwest', 'US', 'pre-launch'),
  ('milwaukee', 'Milwaukee', 'Midwest', 'US', 'pre-launch'),
  ('kansas-city', 'Kansas City', 'Midwest', 'US', 'pre-launch'),
  ('st-louis', 'St. Louis', 'Midwest', 'US', 'pre-launch'),
  ('indianapolis', 'Indianapolis', 'Midwest', 'US', 'pre-launch'),
  ('cincinnati', 'Cincinnati', 'Midwest', 'US', 'pre-launch'),
  ('seattle', 'Seattle', 'West', 'US', 'pre-launch'),
  ('portland', 'Portland', 'West', 'US', 'pre-launch'),
  ('sacramento', 'Sacramento', 'West', 'US', 'pre-launch'),
  ('san-francisco', 'San Francisco', 'West', 'US', 'pre-launch'),
  ('salt-lake-city', 'Salt Lake City', 'West', 'US', 'pre-launch'),
  ('boise', 'Boise', 'West', 'US', 'pre-launch'),
  ('new-orleans', 'New Orleans', 'South', 'US', 'pre-launch'),
  ('memphis', 'Memphis', 'South', 'US', 'pre-launch'),
  ('richmond', 'Richmond', 'Southeast', 'US', 'pre-launch'),
  ('charleston', 'Charleston', 'Southeast', 'US', 'pre-launch'),
  ('savannah', 'Savannah', 'Southeast', 'US', 'pre-launch'),
  ('birmingham', 'Birmingham', 'Southeast', 'US', 'pre-launch'),
  ('oklahoma-city', 'Oklahoma City', 'South', 'US', 'pre-launch'),
  ('tulsa', 'Tulsa', 'South', 'US', 'pre-launch'),
  ('albuquerque', 'Albuquerque', 'West', 'US', 'pre-launch'),
  ('montreal', 'Montreal', 'Quebec', 'CA', 'pre-launch'),
  ('ottawa', 'Ottawa', 'Ontario', 'CA', 'pre-launch'),
  ('edmonton', 'Edmonton', 'Alberta', 'CA', 'pre-launch');
